# services:
#   coinark-client:
#     container_name: coinark-client
#     build:
#       context: ./client
#       dockerfile: Dockerfile
#     ports:
#       - 80:3000
#   coinark-server:
#     container_name: coinark-server
#     build:
#       context: ./lostark
#       dockerfile: Dockerfile
#     ports:
#       - 4000:4000

# docker-compose up -d --build

version: '3.7'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs 
      - ./vhost:/etc/nginx/vhost.d 
      - ./html:/usr/share/nginx/html 
      
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
    environment:
        - DEFAULT_EMAIL=garyie13@live.com
        
  coinark-frontend:
    image: ghcr.io/utscc09/coinark-frontend:main
    container_name: coinark-frontend
    restart: always
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=coinark.garyxie.me
      - LETSENCRYPT_HOST=coinark.garyxie.me
      
  coinark-backend:
    image: ghcr.io/utscc09/coinark-backend:main
    container_name: coinark-backend
    restart: always
    expose:
      - 4000
    environment:
      - VIRTUAL_HOST=api.coinark.garyxie.me
      - LETSENCRYPT_HOST=api.coinark.garyxie.me
      - NODE_ENV
      - MONGO_PASS
      - SECRET
